{{- if .Values.SsoRelay.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.SsoRelay.controller.name}}
  namespace: {{ include "ssorelay.namespace" . | quote }}
  labels: {{- include "ssorelay.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.SsoRelay.controller.replicas }}
  selector:
    matchLabels: {{- include "ssorelay.selector.labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "ssorelay.labels" . | nindent 8 }}
      {{- with .Values.SsoRelay.controller.annotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{.Values.SsoRelay.controller.name}}
      {{- with .Values.SsoRelay.controller.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.SsoRelay.controller.securityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.SsoRelay.controller.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.SsoRelay.controller.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: encryption-key
          secret:
            secretName: {{ .Values.SsoRelay.controller.name }}
            optional: true
        - name: trusted-controllers
          configMap:
            name: {{ include "ssorelay.configmapname" . | quote }}
      containers:
        - name: "service"
          image: "{{ .Values.SsoRelay.controller.image.registry | default .Values.Common.image.registry }}/{{ .Values.SsoRelay.controller.image.repository }}{{- with .Values.SsoRelay.controller.image.tag | default .Values.Common.image.tag -}}{{- if eq (substr 0 7 .) "sha256:" -}}@{{.}}{{- else -}}:{{.}}{{- end -}}{{- end -}}"
          imagePullPolicy: {{ .Values.SsoRelay.controller.image.pullPolicy | quote}}
          {{- if .Values.SsoRelay.controller.javaOpts }}
          env:
            - name: JAVA_OPTS
              value : {{ .Values.SsoRelay.controller.javaOpts | quote }}
          {{- end }}
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          {{- with .Values.SsoRelay.controller.container.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.SsoRelay.controller.container.securityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            periodSeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            periodSeconds: 30
            timeoutSeconds: 5
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: encryption-key
              mountPath: /var/cloudbees-sso-relay/encryption-key
              readOnly: true
            - name: trusted-controllers
              mountPath: /var/cloudbees-sso-relay/config
              readOnly: true
{{- end }}
