{{- if and (.Values.SsoRelay.enabled) (include "cloudbees-core.needs-ingress" .) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.SsoRelay.controller.name}}
  namespace: {{ include "ssorelay.namespace" . | quote }}
  labels: {{- include "ssorelay.labels" . | nindent 4 }}
  annotations: {{- include "ssorelay.ingress.annotations" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.OperationsCenter.Ingress.Class | quote }}
  rules:
  - host: {{ include "ssorelay.hostnamewithoutport" . | quote }}
    http:
      paths:
      - path: {{ include "ssorelay.contextpath" . | quote }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.SsoRelay.controller.name }}
            port:
              number: 80
  {{- if .Values.OperationsCenter.Ingress.tls.Enable }}
  tls:
  - hosts:
    - {{ include "ssorelay.hostnamewithoutport" . | quote }}
    secretName: {{ .Values.OperationsCenter.Ingress.tls.SecretName }}
  {{- end -}}
{{- end }}
