{{- if and (.Values.SsoRelay.enabled) (include "cloudbees-core.needs-routes" .) }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{.Values.SsoRelay.controller.name}}
  namespace: {{ include "ssorelay.namespace" . | quote }}
  labels: {{- include "ssorelay.labels" . | nindent 4 }}
spec:
  host: {{ include "ssorelay.hostnamewithoutport" . | quote }}
  path: {{ include "ssorelay.contextpath" . | quote }}
  to:
    kind: Service
    name: {{.Values.SsoRelay.controller.name}}
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
{{ include "openshift.tls" . | indent 2 }}
{{- end -}}
