{{- if .Values.SsoRelay.enabled }}
# A random string used to seed an AES encryption key
{{- $seed := (randAscii 256) | b64enc }}
{{- $secret := (lookup "v1" "Secret" (include "ssorelay.namespace" .) .Values.SsoRelay.controller.name) }}
{{- if $secret }}
{{- if (index $secret.data "seed") }}
{{- $seed = index $secret.data "seed" }}
{{- end }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.SsoRelay.controller.name }}
  namespace: {{ include "ssorelay.namespace" . | quote }}
  labels: {{- include "ssorelay.labels" . | nindent 4 }}
type: Opaque
data:
  seed: {{ $seed }}
{{- end }}
