{{- if .Values.SsoRelay.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.SsoRelay.controller.name}}
  namespace: {{ include "ssorelay.namespace" . | quote }}
  labels: {{- include "ssorelay.labels" . | nindent 4 }}
{{- with .Values.SsoRelay.controller.imagePullSecrets }}
imagePullSecrets:
{{- if kindIs "string" . }}
- name: {{ . }}
{{- else }}
  {{ toYaml . }}
{{- end }}
{{- end }}
{{- end }}
