{{- if .Values.CascBundleService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cascBundleService.serviceName" . }}
  namespace: {{ default .Release.Namespace .Values.Master.OperationsCenterNamespace }}
  labels:
    app: {{ include "cascBundleService.globalName" . }}
{{ include "cloudbees-core.labels" . | indent 4 }}
spec:
  ports:
  - name: {{ .Values.OperationsCenter.ServicePortName }}
    port: 80
    protocol: TCP
    targetPort: {{ include "cascBundleService.containerPort" . }}
  selector:
    app: {{  include "cascBundleService.globalName" . }}
  type: {{ .Values.OperationsCenter.ServiceType }}
{{- end -}}
