{{- if .Values.CascBundleService.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cascBundleService.serviceAccount" . }}
  namespace: {{ default .Release.Namespace .Values.Master.OperationsCenterNamespace }}
  labels:
{{ include "cloudbees-core.labels" . | indent 4 }}
{{- if .Values.CascBundleService.imagePullSecrets }}
imagePullSecrets:
{{- if kindIs "string" .Values.CascBundleService.imagePullSecrets }}
- name: {{ .Values.CascBundleService.imagePullSecrets }}
{{- else }}
{{ toYaml .Values.CascBundleService.imagePullSecrets }}
{{- end -}}
{{- end -}}
{{- end -}}
