{{- if .Values.CascBundleService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cascBundleService.globalName" . }}
  namespace: {{ default .Release.Namespace .Values.Master.OperationsCenterNamespace }}
  labels:
    app: {{ include "cascBundleService.globalName" . }}
{{ include "cloudbees-core.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.CascBundleService.replicas }}
  selector:
    matchLabels:
      app: {{ include "cascBundleService.globalName" . }}
  template:
    metadata:
      {{- with .Values.CascBundleService.annotations}}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "cascBundleService.globalName" . }}
{{ include "cloudbees-core.labels" . | indent 8 }}
    spec:
      {{- with .Values.CascBundleService.podSecurityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        nodeAffinity:
          # Schedule on linux nodes only.
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              # Prefer nodes where there are no masters
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: com.cloudbees.cje.type
                      operator: In
                      values:
                        - master
            - weight: 1
              # Prefer nodes where there are no agents
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: jenkins
                      operator: In
                      values:
                        - slave
      containers:
      - name: {{ include "cascBundleService.globalName" . }}
        image: {{ include "cascBundleService.image" . }}
        imagePullPolicy: {{ .Values.CascBundleService.image.pullPolicy }}
        {{- with .Values.CascBundleService.containerSecurityContext }}
        securityContext: {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
          - containerPort: {{ include "cascBundleService.containerPort" . }}
            name: {{ .Values.OperationsCenter.ContainerPortName }}
            protocol: TCP
        resources: {{- include "cascBundleService.resources" . | nindent 10 }}
        env:
          - name: JAVA_OPTS
            value: >-
              -Dcasc.bundle.service.ssh.strictHostKeyChecking={{ .Values.CascBundleService.ssh.strictHostKeyCheckingEnabled }}
              -Dcasc.bundle.service.autoversioning={{ .Values.CascBundleService.autoversioning }}
              -Dcasc.bundle.service.poll.schedule={{ .Values.CascBundleService.pollingSchedule }}
              {{- with .Values.CascBundleService.credentialSecretsNamespace }}
              -Dcasc.bundle.service.k8sCredentialSecretsNamespace={{ . }}
              {{- end }}
              {{- with .Values.CascBundleService.javaOpts }}
              {{ . }}
              {{- end }}
        volumeMounts:
          - name: tmp
            mountPath: /tmp
          - name: files
            mountPath: /var/casc-bundle-service/files
          - name: casc-bundle-service-config
            mountPath: /var/casc-bundle-service/config
            readOnly: true
          - name: id-token
            mountPath: /var/run/secrets/tokens
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: {{ include "cascBundleService.containerPort" . }}
          periodSeconds: 30
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: {{ include "cascBundleService.containerPort" . }}
          periodSeconds: 30
          timeoutSeconds: 5
      volumes:
        - name: tmp
          emptyDir: { }
        - name: files
          emptyDir: { }
        - name: casc-bundle-service-config
          secret:
            secretName: casc-bundle-service-config
        - name: id-token
          projected:
            sources:
            - serviceAccountToken:
                path: id-token
                expirationSeconds: 600
                audience: controllers
      serviceAccountName: {{ include "cascBundleService.serviceAccount" . }}
      {{- with .Values.CascBundleService.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.CascBundleService.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
{{- else }}
# Casc Bundle Service is not enabled
{{- end -}}
