{{- if .Values.OperationsCenter.CasC.Retriever.Enabled }}
{{- if include "cloudbees-core.needs-routes" . -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: casc-retriever-sidecar-svc
  labels:
{{ include "cloudbees-core.labels" . | indent 4 }}
spec:
{{- if (include "oc.hostnamewithoutport" . ) }}
  host: {{ include "oc.hostnamewithoutport" . | quote }}
{{- end }}
  path: /casc-retriever
  to:
    kind: Service
    name: casc-retriever-sidecar-svc
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
{{ include "openshift.tls" . | indent 2 }}
{{- end -}}
{{- end -}}
