{{- if .Values.CascBundleService.enabled }}
{{- $targetNamespace := (default .Release.Namespace .Values.Master.OperationsCenterNamespace) -}}
{{- $configmap := (lookup "v1" "ConfigMap" $targetNamespace "service-account-casc-bundle") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-account-casc-bundle
  namespace: {{ default .Release.Namespace .Values.Master.OperationsCenterNamespace }}
  labels:
    app: {{ include "cascBundleService.globalName" .  }}
{{ include "cloudbees-core.labels" . | indent 4 }}
{{ if and $configmap $configmap.data -}}
data:
  {{ $configmap.data | toYaml }}
{{ end -}}
{{- end -}}
