{{- if .Values.OperationsCenter.CasC.Retriever.Enabled }}
apiVersion: v1
kind: Service
metadata:
  name: casc-retriever-sidecar-svc
  labels: {{- include "cloudbees-core.labels" . | nindent 4 }}
  {{- with (include "casc-retriever.service.annotations" .) }}
  annotations: {{- . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/component: cjoc
    com.cloudbees.cje.tenant: cjoc
  ports:
    - name: {{ .Values.OperationsCenter.ServicePortName }}
      protocol: TCP
      port: 80
      targetPort: {{ .Values.OperationsCenter.CasC.Retriever.containerPort }}
{{- end -}}

