{{- if and .Values.CascBundleService.enabled .Values.CascBundleService.createConfig }}
{{- $targetNamespace := (default .Release.Namespace .Values.Master.OperationsCenterNamespace) -}}
{{- $secret := (lookup "v1" "Secret" $targetNamespace "casc-bundle-service-config") -}}
apiVersion: v1
kind: Secret
metadata:
  name: casc-bundle-service-config
  namespace: {{ default .Release.Namespace .Values.Master.OperationsCenterNamespace }}
  labels:
    app: {{ include "cascBundleService.globalName" .  }}
{{ include "cloudbees-core.labels" . | indent 4 }}
type: Opaque
{{ if and $secret (index $secret.data "service-configuration.yaml") -}}
data:
  service-configuration.yaml: {{ index $secret.data "service-configuration.yaml" }}
{{ else -}}
stringData:
  service-configuration.yaml: |
    connectors:
    credentials:
{{- end -}}
{{- else -}}
# casc-bundle-service-config creation skipped
{{- end -}}
