{{- if and .Values.CascBundleService.enabled .Values.CascBundleService.credentialSecretsNamespace}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: casc-bundle-service-rolebinding-credentialSecretsNamespace
  namespace: {{ .Values.CascBundleService.credentialSecretsNamespace}}
  labels:
{{ include "cloudbees-core.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: casc-bundle-service-credentialSecretsNamespace
subjects:
- kind: ServiceAccount
  name: {{ include "cascBundleService.serviceAccount" . }}
  namespace: {{ default .Release.Namespace .Values.Master.OperationsCenterNamespace }}
{{- end -}}
