{{ template "validate.operationscenter" . }}
{{- if and (or .Values.OperationsCenter.Enabled .Values.Master.OperationsCenterNamespace) (.Values.rbac.install) (.Values.SsoRelay.enabled) -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cjoc-sso-relay
  labels: {{- include "cloudbees-core.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cjoc-sso-relay
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: {{ default .Release.Namespace .Values.Master.OperationsCenterNamespace }}
{{- include "rbac.group-subject" . }}
{{- end }}
