{{ template "validate.operationscenter" . }}
{{- if and .Values.rbac.install .Values.CascBundleService.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cjoc-configmaps-role
  namespace: {{ default .Release.Namespace .Values.Master.OperationsCenterNamespace }}
  labels:
{{ include "cloudbees-core.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - update
{{- end }}
