{{- if .Values.Hibernation.Protected -}}
{{- $secretb64 := (randAlpha 10) | lower | b64enc }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "managed-master-hibernation-monitor-protected") }}
{{- if $secret }}
  {{- if (index $secret.data "secret") }}
    {{- $secretb64 = index $secret.data "secret" }}
  {{- end -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: managed-master-hibernation-monitor-protected
  labels:
    app: managed-master-hibernation-monitor
    # TODO app.kubernetes.io/component?
{{ include "cloudbees-core.labels" . | indent 4 }}
type: Opaque
data:
  secret: {{ $secretb64 }}
{{- end -}}
