{{- if .Values.PluggableStorageService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: pluggable-storage-service
  namespace: {{ default .Release.Namespace .Values.Master.OperationsCenterNamespace }}
  labels:
{{ include "cloudbees-core.labels" . | indent 4 }}
    app: pluggable-storage-service
spec:
  ports:
  - name: {{ .Values.OperationsCenter.ServicePortName }}
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: pluggable-storage-service
  type: {{ .Values.OperationsCenter.ServiceType }}
{{- end -}}
