{{- if .Values.PluggableStorageService.enabled -}}
{{- if .Values.rbac.install -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.pluggableStorageServiceServiceAccountName }}
  namespace: {{ default .Release.Namespace .Values.Master.OperationsCenterNamespace }}
  {{- if .Values.rbac.pluggableStorageServiceServiceAccountAnnotations }}
  annotations:
{{ toYaml .Values.rbac.pluggableStorageServiceServiceAccountAnnotations | indent 4 }}
{{- end }}
  labels:
{{ include "cloudbees-core.labels" . | indent 4 }}
{{- if .Values.PluggableStorageService.imagePullSecrets }}
imagePullSecrets:
{{- if kindIs "string" .Values.PluggableStorageService.imagePullSecrets }}
- name: {{ .Values.PluggableStorageService.imagePullSecrets }}
{{- else }}
{{ toYaml .Values.PluggableStorageService.imagePullSecrets }}
{{- end}}
{{- end -}}
{{- end -}}
{{- end -}}
