apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: cjoc-backend-config
  namespace: cloudbees-gatewayapi
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /cjoc/health/
    port: 8080
